#Positions of the floating texts
Positions:
    - world: Factions
      x: 234
      "y": 75
      z: 187
    - world: Spawn
      x: 2
      "y": 0
      z: 0
#API-Key of your server provided by minecraftpocket-servers.com
API-Key: ""
#Amount of voters who shall be shown (Max: 500)
Amount: 9
#Update interval of the query to the server in seconds
Update-Interval: 1800
#Header of the floating text particle
Header: "§eTop voters of the month"
#Text for every row after the header
Text: "§6{player} §b{votes}"
#Check if the name of a voter is valid
#Votes of invalidly named players will be discarded if enabled
Check-Name: true
